export type EquipmentEntry = {
  slug: string;
  name: string;
  category: string;
  image: string;
  imageAlt: string;
  what: string;
  signs: string[];
  maintenance: string[];
  lifespan: string;
  serviceHref: string;
  serviceLabel: string;
};

export const equipmentLibrary: EquipmentEntry[] = [
  {
    slug: "rooftop-unit",
    name: "Rooftop Unit (RTU)",
    category: "HVAC",
    image: "/equipment-renders/rooftop-unit.webp",
    imageAlt: "3D cutaway render of a packaged rooftop HVAC unit",
    what: "A packaged heating and cooling box that sits on the roof and conditions the floors below. Most commercial buildings run several, each serving its own zone.",
    signs: ["Uneven temperatures between zones", "Short cycling or constant running", "Rising energy bills with no usage change"],
    maintenance: ["Quarterly filter changes and coil cleaning", "Belt, bearing, and economizer checks each season", "Refrigerant charge verified annually"],
    lifespan: "15–20 years",
    serviceHref: "/mechanical/hvac",
    serviceLabel: "HVAC & Heat Pumps",
  },
  {
    slug: "boiler",
    name: "Boiler",
    category: "Mechanical",
    image: "/equipment-renders/boiler.webp",
    imageAlt: "3D cutaway render of a commercial boiler",
    what: "Heats water that gets pumped through the building for space heating, and often for domestic hot water. The heart of most older BC buildings.",
    signs: ["Banging or kettling noises", "Pressure swings on the gauge", "Some suites warm, others cold"],
    maintenance: ["Annual combustion analysis and tune", "Water treatment checks to prevent scale", "Relief valve and control testing"],
    lifespan: "20–30 years",
    serviceHref: "/mechanical/gas",
    serviceLabel: "Gas & Hydronics",
  },
  {
    slug: "heat-pump",
    name: "Heat Pump",
    category: "HVAC",
    image: "/equipment-renders/heat-pump.webp",
    imageAlt: "3D cutaway render of a commercial heat pump",
    what: "Moves heat instead of burning fuel: heating in winter, cooling in summer, from one machine. The centrepiece of most electrification retrofits.",
    signs: ["Ice on the outdoor unit in mild weather", "Backup heat running constantly", "Declining heating output below 0°C"],
    maintenance: ["Coil cleaning and filter changes twice a year", "Defrost cycle and refrigerant checks annually", "Condensate drain clearing"],
    lifespan: "12–18 years",
    serviceHref: "/mechanical/hvac",
    serviceLabel: "HVAC & Heat Pumps",
  },
  {
    slug: "air-handler",
    name: "Air Handling Unit (AHU)",
    category: "HVAC",
    image: "/equipment-renders/air-handler.webp",
    imageAlt: "3D cutaway render of a commercial air handling unit",
    what: "The big box that moves air through the building: fans, filters, and coils that heat or cool air before ducts distribute it.",
    signs: ["Weak airflow at diffusers", "Whistling or rumbling from shafts", "Stale air and stuffy corridors"],
    maintenance: ["Filter changes on schedule, not on failure", "Fan belt and bearing inspection", "Coil cleaning and damper calibration"],
    lifespan: "20–30 years",
    serviceHref: "/mechanical/hvac",
    serviceLabel: "HVAC & Heat Pumps",
  },
  {
    slug: "cooling-tower",
    name: "Cooling Tower",
    category: "HVAC",
    image: "/equipment-renders/cooling-tower.webp",
    imageAlt: "3D cutaway render of a rooftop cooling tower",
    what: "Rejects building heat to the outdoors using evaporating water. Paired with chillers or water-source heat pump loops in larger buildings.",
    signs: ["Loop temperatures creeping up", "Scale or algae visible in the basin", "Drift or splash-out on the roof"],
    maintenance: ["Water treatment program, verified monthly", "Basin cleaning and fill inspection", "Fan and drive service each season"],
    lifespan: "15–25 years",
    serviceHref: "/mechanical/hvac",
    serviceLabel: "HVAC & Heat Pumps",
  },
  {
    slug: "compressor",
    name: "Compressor",
    category: "Refrigeration",
    image: "/equipment-renders/compressor.webp",
    imageAlt: "3D cutaway render of a refrigerant compressor",
    what: "The pump at the heart of every AC, heat pump, and refrigeration system. When a quote says 'replace compressor,' this is the part doing the pushing.",
    signs: ["Hard starts, clicks, or tripped breakers", "Warm air from a system that should cool", "Oil stains around the unit"],
    maintenance: ["Refrigerant charge and superheat checked annually", "Electrical connections tightened and tested", "Vibration and amp-draw trending"],
    lifespan: "10–15 years",
    serviceHref: "/mechanical/refrigeration",
    serviceLabel: "Refrigeration",
  },
  {
    slug: "electrical-panel",
    name: "Electrical Panel & Switchgear",
    category: "Electrical",
    image: "/equipment-renders/electrical-panel.webp",
    imageAlt: "3D cutaway render of commercial electrical panel and switchgear",
    what: "Where power enters the building and gets split to every circuit. Panels distribute; switchgear protects and meters the heavy loads.",
    signs: ["Warm breakers or a burning smell", "Frequent nuisance trips", "No spare capacity for EV or HVAC upgrades"],
    maintenance: ["Infrared scan annually to find hot lugs", "Torque checks on connections", "Breaker exercise and labelling audit"],
    lifespan: "30–40 years",
    serviceHref: "/electrical/electrical",
    serviceLabel: "Commercial Electrical",
  },
  {
    slug: "controls",
    name: "Building Controls (BAS)",
    category: "Controls",
    image: "/equipment-renders/controls.webp",
    imageAlt: "3D cutaway render of a building automation control panel",
    what: "The brain that schedules and balances everything else: setpoints, schedules, alarms, and the data that tells you something's drifting.",
    signs: ["Equipment running around the clock", "Occupants overriding thermostats", "Alarms nobody is watching"],
    maintenance: ["Sensor calibration annually", "Schedule and setpoint review each season", "Trend log review for slow drift"],
    lifespan: "10–15 years",
    serviceHref: "/electrical/low-voltage",
    serviceLabel: "Low Voltage & Controls",
  },
  {
    slug: "pump",
    name: "Pumps",
    category: "Mechanical",
    image: "/equipment-renders/pump.webp",
    imageAlt: "3D cutaway render of a mechanical circulation pump",
    what: "Circulate heating water, domestic water, and drainage. Quiet, invisible, and the first thing residents notice when they stop.",
    signs: ["Seal drips or rust trails", "Noise or vibration changes", "Dead legs and cold radiators"],
    maintenance: ["Seal and coupling inspection", "Bearing lubrication on schedule", "Amp draw and flow verification"],
    lifespan: "10–20 years",
    serviceHref: "/mechanical/plumbing",
    serviceLabel: "Plumbing",
  },
  {
    slug: "gas-heater",
    name: "Gas Unit Heater",
    category: "Gas",
    image: "/equipment-renders/gas-heater.webp",
    imageAlt: "3D cutaway render of a suspended gas unit heater",
    what: "The suspended heaters that keep warehouses, parkades, and shops workable through winter, burning natural gas with a fan behind it.",
    signs: ["Yellow or lazy flame", "Heat exchanger corrosion", "Smell of combustion in the space"],
    maintenance: ["Annual combustion analysis", "Heat exchanger inspection", "Venting and clearance checks"],
    lifespan: "15–20 years",
    serviceHref: "/mechanical/gas",
    serviceLabel: "Gas Services",
  },
  {
    slug: "generator",
    name: "Standby Generator",
    category: "Power",
    image: "/equipment-renders/generator.webp",
    imageAlt: "3D cutaway render of a standby diesel generator",
    what: "Life-safety power when the grid fails: elevators, exit lighting, fire pumps, and heat. In BC, annual CSA C282 testing is the law for many buildings.",
    signs: ["Failed or skipped exercise runs", "Wet-stacking from light loading", "Aging fuel that's never been polished"],
    maintenance: ["Annual CSA C282 load-bank test", "Oil, coolant, and battery service", "Fuel polishing on rotation"],
    lifespan: "25–35 years",
    serviceHref: "/power/generators",
    serviceLabel: "Standby Generators",
  },
  {
    slug: "transfer-switch",
    name: "Automatic Transfer Switch (ATS)",
    category: "Power",
    image: "/equipment-renders/transfer-switch.webp",
    imageAlt: "3D cutaway render of an automatic transfer switch",
    what: "Decides when the building runs on grid or generator, and makes the swap automatically. A generator with a failed ATS is a very expensive lawn ornament.",
    signs: ["Failure to transfer during tests", "Chatter or hum from the cabinet", "Obsolete controller with no parts support"],
    maintenance: ["Transfer-time testing annually", "Infrared scan of lugs and contacts", "Exercise clock verification"],
    lifespan: "20–30 years",
    serviceHref: "/power/transfer-switches",
    serviceLabel: "Transfer Switches",
  },
  {
    slug: "building-envelope",
    name: "Roof Membrane & Envelope",
    category: "Building Envelope",
    image: "/equipment-renders/building-envelope.webp",
    imageAlt: "3D cutaway render of a flat roof assembly with membrane layers",
    what: "The layered system keeping water out of the building: deck, vapour barrier, insulation, and membrane, plus the flashings, drains, and sealant joints where most leaks actually start.",
    signs: ["Ponding water that outlasts the rain", "Stains on top-floor ceilings", "Blisters, cracks, or open laps in the membrane"],
    maintenance: ["Annual roof and drain inspection, spring and fall", "Sealant joint review on a rotating cycle", "Moisture scans to find wet insulation before it spreads"],
    lifespan: "20–30 years",
    serviceHref: "/build/envelope",
    serviceLabel: "Building Envelope",
  },
  {
    slug: "ev-charger",
    name: "EV Charging Station",
    category: "Electrical",
    image: "/equipment-renders/ev-charger.webp",
    imageAlt: "Commercial dual-port EV charging station cutaway",
    what: "Level 2 charging for residents, tenants, and fleets: the pedestal, the electronics inside it, and the load management that lets a building charge many cars without a service upgrade.",
    signs: ["Charging sessions that stop early", "Breaker trips when several cars charge", "Damaged cables or connectors"],
    maintenance: ["Annual inspection of contactors and terminations", "Cable and connector condition checks", "Load-management settings verified against panel capacity"],
    lifespan: "10–15 years",
    serviceHref: "/electrical/ev-chargers",
    serviceLabel: "EV Charger Installs",
  },
  {
    slug: "led-lighting",
    name: "LED Lighting & Controls",
    category: "Electrical",
    image: "/equipment-renders/led-lighting.webp",
    imageAlt: "Industrial LED high-bay fixture cutaway",
    what: "High-bay, troffer, and common-area LED fixtures with the drivers and sensors that run them. The retrofit that pays for itself, and then needs looking after.",
    signs: ["Flickering or dark fixtures", "Sensors that never switch off, or never on", "Sections dimming unevenly"],
    maintenance: ["Driver and connection inspection on failures", "Sensor calibration and coverage checks", "Lens cleaning in dusty spaces"],
    lifespan: "10–15 years",
    serviceHref: "/electrical/led-lighting",
    serviceLabel: "LED Lighting Retrofits",
  },
  {
    slug: "loading-dock",
    name: "Loading Dock Equipment",
    category: "Building",
    image: "/equipment-renders/loading-dock.webp",
    imageAlt: "Warehouse loading dock cutaway with door and leveler",
    what: "Overhead doors, levelers, seals, and bumpers: the hardest-working equipment in a warehouse, cycled dozens of times a day and ignored until a door won't close.",
    signs: ["Doors that bind, slam, or won't seal", "Levelers that drift or bang under load", "Torn seals letting weather in"],
    maintenance: ["Spring, cable, and track inspection quarterly", "Leveler hydraulic service annually", "Seal and bumper replacement on wear"],
    lifespan: "10–20 years",
    serviceHref: "/build/property-services",
    serviceLabel: "Property Services",
  },
  {
    slug: "fan-coil",
    name: "Fan Coil Unit",
    category: "HVAC",
    image: "/equipment-renders/fan-coil.webp",
    imageAlt: "Ceiling fan coil unit cutaway",
    what: "The in-suite heating and cooling workhorse of strata towers: a coil, a fan, a filter, and a drain pan hiding above the ceiling of almost every condo bedroom hallway.",
    signs: ["Water stains on the ceiling below", "Weak airflow or noisy fan", "Suites that never reach setpoint"],
    maintenance: ["Filter changes 2–4 times per year", "Coil cleaning and drain pan treatment annually", "Valve and control checks each season"],
    lifespan: "15–20 years",
    serviceHref: "/mechanical/hvac",
    serviceLabel: "HVAC & Heat Pumps",
  },
  {
    slug: "water-heater",
    name: "Hot Water Heater",
    category: "Mechanical",
    image: "/equipment-renders/water-heater.webp",
    imageAlt: "Cutaway of a gas hot water tank and tankless water heater",
    what: "Tank or tankless, the appliance that decides whether the morning shower is fine or freezing — and one of the most common sources of water damage when it fails unnoticed.",
    signs: ["Rusty or lukewarm water", "Rumbling or popping from the tank", "Moisture around the base"],
    maintenance: ["Annual flush to clear sediment", "Anode rod check every 2–3 years", "T&P valve test annually"],
    lifespan: "8–12 years (tank) · 15–20 (tankless)",
    serviceHref: "/mechanical/plumbing",
    serviceLabel: "Plumbing & Hot Water",
  },
];

export function getEquipment(slug: string) {

  return equipmentLibrary.find((e) => e.slug === slug);
}