import type { EquipmentPart } from "@/components/EquipmentHotspotFigure";

export const equipmentInteractive: Record<string, { image: string; alt: string; parts: EquipmentPart[] }> = {
  "rooftop-unit": {
    image: "/equipment-renders/rooftop-unit.webp",
    alt: "3D render of a packaged rooftop HVAC unit",
    parts: [
      {
        id: "compressor",
        name: "Compressor",
        what: "The pump that pushes refrigerant through the system. The heart of the cooling side, hidden behind the access panel.",
        goesWrong: "Hard starts, tripped breakers, and burnout — usually from low refrigerant, dirty coils, or electrical faults left too long. The most expensive single failure on the unit.",
        symptoms: "Warm supply air, breaker trips, loud starts, short cycling.",
        action: "Amp-draw and refrigerant checks each PM visit; replace contactor and capacitors early, replace compressor only with root cause fixed.",
        cx: 35,
        cy: 38,
      },
      {
        id: "condenser",
        name: "Condenser coil",
        what: "The louvered section that rejects heat outdoors. Air is pulled through these fins by the fans above.",
        goesWrong: "Clogs with dirt, pollen, and cottonwood. Head pressure climbs, efficiency drops, and the compressor works harder until something gives.",
        symptoms: "Rising head pressure, unit running longer on mild days, high energy use.",
        action: "Coil wash every spring; comb bent fins; keep cottonwood screens clear.",
        cx: 20.6,
        cy: 35.0,
      },
      {
        id: "fans",
        name: "Condenser fans",
        what: "Draw outdoor air across the condenser coil to dump the building's heat.",
        goesWrong: "Motor bearings seize and blades crack from vibration. A dead fan on a hot day means high-pressure lockout, and no cooling.",
        symptoms: "Grinding or clicking above the roof, tripped high-pressure lockouts on hot days.",
        action: "Bearing and blade inspection each PM; replace motors on condition, not on failure.",
        cx: 27.7,
        cy: 19.3,
      },
      {
        id: "filters",
        name: "Filters & blower",
        what: "Behind this access door: the air filters and the supply blower that pushes conditioned air into the ductwork.",
        goesWrong: "Neglected filters choke airflow, freeze coils, and strain belts and bearings. The cheapest part causes the most avoidable failures.",
        symptoms: "Weak airflow, whistling at grilles, iced coil, musty smell.",
        action: "Filter change on schedule (quarterly for most buildings); airflow verified after.",
        cx: 51.2,
        cy: 41.9,
      },
      {
        id: "economizer",
        name: "Economizer hood",
        what: "Dampers that pull in outside air for free cooling when the weather is right.",
        goesWrong: "Dampers seize and actuators fail quietly — you pay for mechanical cooling that BC's climate would give you free.",
        symptoms: "Cooling running on cool days, stuffy air, dampers visibly stuck.",
        action: "Actuator stroke test and linkage lube annually; verify minimum outdoor-air position.",
        cx: 58.9,
        cy: 43.0,
      },
      {
        id: "gasheat",
        name: "Gas heat section",
        what: "The gas-fired heat exchanger and flue that handle heating season.",
        goesWrong: "Heat exchangers crack with age and cycling, a carbon monoxide risk. Annual combustion analysis catches it first.",
        symptoms: "Smell of combustion, short heating cycles, lockout codes at the stat.",
        action: "Annual combustion analysis and heat-exchanger inspection before heating season.",
        cx: 49.4,
        cy: 38.7,
      },
      {
        id: "controls",
        name: "Controls & disconnect",
        what: "Unit controller, contactors, and the service disconnect.",
        goesWrong: "Loose lugs, pitted contactors, and nuisance lockouts. Infrared scans on PM visits find the hot spots before they arc.",
        symptoms: "Nuisance lockouts, dead zones, unit ignoring the schedule.",
        action: "Infrared scan of lugs and contactors; torque terminals; verify sensor calibration.",
        cx: 65.7,
        cy: 53.6,
      },
      {
        id: "ducts",
        name: "Supply & return ducts",
        what: "The collars where the unit connects to the building's ductwork through the roof curb.",
        goesWrong: "Curb seals fail and leak air and water into the roof; poorly sealed collars waste conditioned air.",
        symptoms: "Water stains at the curb, drafts, whistling in the ceiling below.",
        action: "Curb seal and duct-collar inspection on every visit; reseal before roofing damage spreads.",
        cx: 69.9,
        cy: 38.3,
      },
    ],
  },
  "generator": {
    image: "/equipment-renders/generator.webp",
    alt: "3D render of a skid-mounted standby generator",
    parts: [
      {
        id: "engine",
        name: "Engine",
        what: "The diesel or natural-gas engine that spins the alternator when the grid fails.",
        goesWrong: "Oil and coolant leaks, and wet-stacking from running too lightly loaded. Annual load-bank testing burns it clean and proves full output.",
        symptoms: "Oil spots under the set, blue-black exhaust, hard starts on exercise runs.",
        action: "Oil and filter service annually; load-bank test to burn off wet-stacking; fix leaks at gaskets early.",
        cx: 43,
        cy: 32,
      },
      {
        id: "radiator",
        name: "Radiator & coolant",
        what: "Keeps the engine at temperature under full load, with a block heater for instant cold starts.",
        goesWrong: "Failed block heaters and old coolant are a top cause of start failure. Hoses age invisibly until they burst under load.",
        symptoms: "Coolant puddles, cold block in winter, high-temp shutdowns under load.",
        action: "Coolant condition test and block-heater check each service; pressure-test the system annually.",
        cx: 29.8,
        cy: 32.3,
      },
      {
        id: "alternator",
        name: "Alternator",
        what: "Converts engine power into the electricity your life-safety systems run on.",
        goesWrong: "Winding insulation degrades and bearings wear, invisible until under real load. Exactly what CSA C282 load-bank testing exists to catch.",
        symptoms: "Voltage sag under load, insulation smell, bearing whine.",
        action: "CSA C282 annual load-bank test; megger the windings; grease bearings on schedule.",
        cx: 64.4,
        cy: 44.4,
      },
      {
        id: "batteries",
        name: "Starting batteries",
        what: "Crank the engine the moment the transfer switch calls for power.",
        goesWrong: "The single most common reason generators fail to start. Replaced on a 2–3 year cycle and load-tested every visit.",
        symptoms: "Slow crank, clicking start attempts, corroded terminals.",
        action: "Load-test every visit; replace on a 2–3 year cycle regardless of appearance.",
        cx: 24.7,
        cy: 35.0,
      },
      {
        id: "fuel",
        name: "Fuel tank",
        what: "The base tank holds enough fuel for the code-required runtime.",
        goesWrong: "Diesel absorbs water and grows microbes. Contaminated fuel kills injectors mid-outage — polishing keeps it burnable.",
        symptoms: "Water in fuel samples, dark cloudy diesel, clogged filters.",
        action: "Annual fuel sample and polish rotation; biocide dosing; keep tanks topped to limit condensation.",
        cx: 36.4,
        cy: 46.3,
      },
      {
        id: "controller",
        name: "Controller",
        what: "Monitors the grid, starts the set, and reports alarms.",
        goesWrong: "Obsolete controllers with no parts support, and alarm faults nobody is watching. Remote annunciation puts warnings in front of a human.",
        symptoms: "Alarm lights nobody can explain, failed remote starts, blank display.",
        action: "Verify alarms and exercise schedule each visit; add remote annunciation; plan controller retrofits before obsolescence.",
        cx: 74.1,
        cy: 44.6,
      },
      {
        id: "exhaust",
        name: "Exhaust & silencer",
        what: "Carries combustion gases out and keeps the noise neighbourly.",
        goesWrong: "Condensation corrodes silencers from the inside; flex sections crack with vibration.",
        symptoms: "Soot streaks, rain caps stuck open, exhaust smell in the room.",
        action: "Inspect silencer and flex sections annually; replace corroded sections before they leak into the enclosure.",
        cx: 53.4,
        cy: 23.1,
      },
    ],
  },
  "boiler": {
    image: "/equipment-renders/boiler.webp",
    alt: "3D render of a commercial hydronic boiler",
    parts: [
      {
        id: "burner",
        name: "Burner",
        what: "Mixes gas and air and fires into the heat exchanger. The business end of the boiler.",
        goesWrong: "Fouled or mis-tuned burners waste fuel and soot up the exchanger. Annual combustion analysis keeps it clean, safe, and efficient.",
        symptoms: "Yellow lazy flame, soot on the jacket, rumbling ignition.",
        action: "Annual combustion analysis and burner tune; clean and gap igniters.",
        cx: 52,
        cy: 30,
      },
      {
        id: "exchanger",
        name: "Heat exchanger",
        what: "The vessel where flame heat transfers into the building's water.",
        goesWrong: "Scale from untreated water insulates the metal until it overheats and cracks. Water treatment is cheaper than a new boiler.",
        symptoms: "Kettling noise, falling efficiency, water in the burner tray.",
        action: "Water treatment verified monthly; descale on condition; eddy-current test older vessels.",
        cx: 40,
        cy: 21,
      },
      {
        id: "gastrain",
        name: "Gas train",
        what: "The regulators and safety shutoff valves feeding the burner.",
        goesWrong: "Valves stick and regulators drift. Annual leak and lockout testing is a code requirement, not a suggestion.",
        symptoms: "Gas smell, lockouts on ignition, regulator hunting.",
        action: "Annual leak test and safety-shutoff proving per code; replace diaphragms on age.",
        cx: 60,
        cy: 44,
      },
      {
        id: "pump",
        name: "Circulation pump",
        what: "Pushes heated water out to the building loop.",
        goesWrong: "Seals weep, bearings whine, couplings wear. A dead pump means a hot boiler and a cold building.",
        symptoms: "Seal drip trails, bearing whine, cold loop with a hot boiler.",
        action: "Seal and coupling inspection each visit; amp-draw trending; rebuild or swap on condition.",
        cx: 56,
        cy: 54,
      },
      {
        id: "relief",
        name: "Relief valve",
        what: "The last-resort safety that dumps pressure before the vessel fails.",
        goesWrong: "They seize with age and mineral deposits. Tested on every service visit, replaced without debate when they fail.",
        symptoms: "Weeping discharge pipe, crusted valve seat, no test tag.",
        action: "Manual lift test annually; replace on any sign of seepage — never cap or plug.",
        cx: 45,
        cy: 50,
      },
      {
        id: "controls",
        name: "Controls & aquastat",
        what: "Sequences firing, temperature, and safeties.",
        goesWrong: "Failed sensors cause short-cycling that beats the boiler to death. Trend logs catch it early.",
        symptoms: "Short cycling, wide temperature swings, stale error codes.",
        action: "Verify aquastat calibration and staging each fall; trend runtimes for drift.",
        cx: 67,
        cy: 27,
      },
      {
        id: "flue",
        name: "Flue & venting",
        what: "Carries combustion gases safely out of the building.",
        goesWrong: "Corrosion and blockage push CO back into the mechanical room. Inspected every service, no exceptions.",
        symptoms: "Condensate stains, white powder corrosion, draft alarms.",
        action: "Visual and draft inspection annually; replace corroded sections; verify clearances.",
        cx: 43,
        cy: 8,
      },
    ],
  },
  "heat-pump": {
    image: "/equipment-renders/heat-pump.webp",
    alt: "3D render of an outdoor heat pump unit",
    parts: [
      {
        id: "fan",
        name: "Fan",
        what: "Moves outdoor air across the coil to absorb or reject heat.",
        goesWrong: "Bearings wear and blades crack; a struggling fan slowly kills the compressor behind it.",
        symptoms: "Blade wobble, chirping bearings, ice sheet on the coil behind it.",
        action: "Blade balance and bearing check each PM; clear debris from the guard.",
        cx: 40,
        cy: 33,
      },
      {
        id: "coil",
        name: "Outdoor coil",
        what: "The fin-and-tube surface that exchanges heat with outside air.",
        goesWrong: "Dirt, leaves, and cottonwood choke it. Dirty coils are the #1 cause of lost capacity.",
        symptoms: "Frost outside defrost cycles, capacity loss, fin damage.",
        action: "Coil wash twice yearly; comb fins; keep vegetation two feet clear.",
        cx: 65,
        cy: 30,
      },
      {
        id: "compressor",
        name: "Compressor",
        what: "Pumps refrigerant between indoor and outdoor coils.",
        goesWrong: "The most expensive failure on the unit, almost always secondary to a cheap neglected cause: dirty coils, low charge, bad contactor.",
        symptoms: "Hard starts, hum-click-trip, warm house on cold mornings.",
        action: "Charge verification and terminal torque annually; fix airflow problems before they kill it.",
        cx: 36,
        cy: 52,
      },
      {
        id: "lineset",
        name: "Refrigerant line set",
        what: "The copper pair carrying refrigerant to the indoor unit.",
        goesWrong: "Vibration rubs holes through poorly-supported lines; slow leaks kill efficiency months before they kill cooling.",
        symptoms: "Oil stains on pipe runs, insulation gaps, capacity fade.",
        action: "Leak-check suspect joints; re-insulate exposed runs; support loose pipe.",
        cx: 49,
        cy: 45,
      },
      {
        id: "controls",
        name: "Controls board",
        what: "Runs staging, safeties, and communication with the indoor unit.",
        goesWrong: "Boards fail from moisture and power surges. A surge protector costs less than one board.",
        symptoms: "Random lockouts, defrost stuck on or off, dead board after storms.",
        action: "Surge protection at the disconnect; firmware and sensor checks annually.",
        cx: 63,
        cy: 55,
      },
      {
        id: "defrost",
        name: "Defrost system",
        what: "Reverses the cycle in winter to melt ice off the coil.",
        goesWrong: "Failed defrost sensors let the unit turn into an ice block, and BC's wet winters find them fast.",
        symptoms: "Ice armor on the unit in wet winter weather, steam clouds mid-cycle absent.",
        action: "Defrost initiation and termination test each fall; replace failed sensors immediately.",
        cx: 72,
        cy: 20,
      },
    ],
  },
  "air-handler": {
    image: "/equipment-renders/air-handler.webp",
    alt: "3D render of a commercial air handling unit",
    parts: [
      {
        id: "filters",
        name: "Filter bank",
        what: "Catches dust before it reaches the coil and the building's air.",
        goesWrong: "The cheapest part causes the most failures: choked filters freeze coils, strain motors, and starve rooms of air.",
        symptoms: "Pressure-drop alarm, dust streaks at diffusers, whistling doors.",
        action: "Change on differential pressure or schedule, whichever first; log every change.",
        cx: 18,
        cy: 38,
      },
      {
        id: "coil",
        name: "Heating / cooling coil",
        what: "Conditions the air stream from the hydronic or refrigerant loop.",
        goesWrong: "Fins clog and freeze; untreated coils corrode from the inside. Cleaned and inspected on every PM visit.",
        symptoms: "Reduced capacity, carryover moisture, dirty-sock smell.",
        action: "Coil clean annually; verify valve operation; treat drain pan biocide tabs.",
        cx: 46,
        cy: 37,
      },
      {
        id: "drainpan",
        name: "Condensate drain",
        what: "Carries away the water a cooling coil pulls out of the air.",
        goesWrong: "Blocked drains overflow into ceilings. Most 'mystery leaks' above a corridor are this.",
        symptoms: "Ceiling stains below the unit, standing water in the pan, smell.",
        action: "Clear the trap and pan every cooling season; verify slope and overflow switch.",
        cx: 47,
        cy: 53,
      },
      {
        id: "blower",
        name: "Blower",
        what: "The fan wheel that pushes air through the ductwork.",
        goesWrong: "Belts stretch, bearings dry out, wheels load up with dirt and go out of balance.",
        symptoms: "Rumble or squeal, airflow drop, belt dust in the cabinet.",
        action: "Belt tension and alignment each visit; balance wheel on vibration.",
        cx: 63,
        cy: 33,
      },
      {
        id: "motor",
        name: "Motor & drive",
        what: "Powers the blower via belts or direct drive.",
        goesWrong: "Worn belts slip quietly for months, cutting airflow while the motor cooks. Amp-draw trending catches it.",
        symptoms: "Hot smell, rising amps, tripped overloads.",
        action: "Amp trending against nameplate; grease bearings; align on belt change.",
        cx: 56,
        cy: 44,
      },
      {
        id: "dampers",
        name: "Dampers & ducts",
        what: "Balance and direct the conditioned air.",
        goesWrong: "Actuators seize and linkages slip out of calibration; rooms go hot and cold while energy is wasted.",
        symptoms: "Rooms hot and cold at the same time, actuators humming at end stop.",
        action: "Stroke every damper annually; re-link slipped linkages; verify BAS feedback.",
        cx: 81,
        cy: 30,
      },
    ],
  },
  "cooling-tower": {
    image: "/equipment-renders/cooling-tower.webp",
    alt: "3D render of a cooling tower",
    parts: [
      {
        id: "fan",
        name: "Fan & drive",
        what: "Pulls air through the tower to evaporate and reject heat.",
        goesWrong: "Gearbox oil and belt failures top the list. Vibration analysis hears the failure before you do.",
        symptoms: "Gearbox whine, vibration alarms, oil sheen in the basin.",
        action: "Oil level and vibration check monthly in season; belt or gearbox service annually.",
        cx: 48,
        cy: 10,
      },
      {
        id: "fill",
        name: "Fill media",
        what: "The honeycomb sheets where water and air actually meet.",
        goesWrong: "Scale and algae clog the passages, cutting capacity. Water treatment keeps the tower a tower, not a scale farm.",
        symptoms: "Rising condenser water temps, visible scale curtains, algae mats.",
        action: "Water treatment verified monthly; replace fill sections on fouling.",
        cx: 38,
        cy: 42,
      },
      {
        id: "basin",
        name: "Basin",
        what: "Collects the cooled water for return to the chillers.",
        goesWrong: "Sludge, corrosion, and biological growth, including Legionella risk. Cleaned and treated on a strict schedule.",
        symptoms: "Sludge banks, overflow at the wrong level, biofilm odor.",
        action: "Basin clean and disinfect at season start and end; Legionella program per guidelines.",
        cx: 40,
        cy: 58,
      },
      {
        id: "distribution",
        name: "Water distribution",
        what: "Nozzles spreading warm water evenly over the fill.",
        goesWrong: "Clogged nozzles channel the water, wrecking efficiency. Checked at every seasonal service.",
        symptoms: "Dry streaks on the fill, uneven splash, hot spots.",
        action: "Nozzle inspection and clean each season; balance flow between cells.",
        cx: 40,
        cy: 26,
      },
      {
        id: "louvers",
        name: "Louvers & drift eliminators",
        what: "Keep water in the tower and splash-out off your roof.",
        goesWrong: "Broken louvers ice up in winter and lose water year-round.",
        symptoms: "Splash-out on the roof, winter ice ridges, broken blades.",
        action: "Louver and eliminator inspection each season; replace broken sections.",
        cx: 66,
        cy: 52,
      },
      {
        id: "pipes",
        name: "Condenser water piping",
        what: "The supply and return connecting tower to plant.",
        goesWrong: "Corrosion and biofilm restrict flow; failed insulation freezes lines in cold snaps.",
        symptoms: "Flow alarms, strainer pressure drop, insulation soak.",
        action: "Strainer blowdown monthly; verify heat trace before freeze-up.",
        cx: 72,
        cy: 45,
      },
    ],
  },
  "compressor": {
    image: "/equipment-renders/compressor.webp",
    alt: "3D render of a semi-hermetic refrigeration compressor",
    parts: [
      {
        id: "motor",
        name: "Motor",
        what: "The electric motor sealed inside the compressor body.",
        goesWrong: "Winding insulation degrades with heat and acid from moisture in the system. Oil tests read its health like blood work.",
        symptoms: "Breaker trips, acid smell in oil, megger readings falling.",
        action: "Annual megger and oil acid test; correct low-voltage and contactor issues early.",
        cx: 42,
        cy: 38,
      },
      {
        id: "valves",
        name: "Valve plate",
        what: "Reed valves that make the pumping action work.",
        goesWrong: "Broken reeds from liquid refrigerant slugging: the compressor runs but stops pumping.",
        symptoms: "Compressor runs but pressures barely move, rattle at the head.",
        action: "Valve-plate inspection on capacity loss; fix liquid floodback first.",
        cx: 61,
        cy: 22,
      },
      {
        id: "oil",
        name: "Oil system",
        what: "Lubricates everything; visible in the sight glass.",
        goesWrong: "Low oil or acidic oil is a countdown. Checked on every visit — the sight glass never lies.",
        symptoms: "Low sight glass, foaming at start, dark oil.",
        action: "Oil level and condition every visit; acid test annually; find the refrigerant problem behind bad oil.",
        cx: 63,
        cy: 51,
      },
      {
        id: "terminals",
        name: "Electrical terminals",
        what: "Where power enters the sealed body.",
        goesWrong: "Loose or corroded terminals arc and burn out. A torque check takes minutes.",
        symptoms: "Burn marks at the box, tripped breakers, pitted lugs.",
        action: "Torque and infrared terminals each PM; replace damaged terminal plates immediately.",
        cx: 28,
        cy: 18,
      },
      {
        id: "suction",
        name: "Suction line",
        what: "Returns low-pressure refrigerant gas from the evaporator.",
        goesWrong: "Frost-back means liquid is coming home to break valve reeds.",
        symptoms: "Frost to the compressor body, oil hammering at start.",
        action: "Superheat check every visit; fix metering and load issues before valves break.",
        cx: 84,
        cy: 34,
      },
      {
        id: "discharge",
        name: "Discharge line",
        what: "Sends hot compressed gas to the condenser.",
        goesWrong: "Excess discharge temperature cooks oil into sludge. High-side readings tell the story.",
        symptoms: "Discharge line too hot to touch, burnt oil smell.",
        action: "Discharge temp trending; clean condenser and correct charge before oil cooks.",
        cx: 79,
        cy: 19,
      },
    ],
  },
  "electrical-panel": {
    image: "/equipment-renders/electrical-panel.webp",
    alt: "3D render of a commercial electrical panelboard lineup",
    parts: [
      {
        id: "main",
        name: "Main breaker",
        what: "The single point that can kill power to everything downstream.",
        goesWrong: "Mains that haven't moved in 20 years weld shut. Exercised on a schedule, or discovered frozen during an emergency.",
        symptoms: "Warm panel front, breaker that has never been exercised, corrosion.",
        action: "Exercise annually on a planned shutdown; infrared scan under load.",
        cx: 37,
        cy: 25,
      },
      {
        id: "branch",
        name: "Branch breakers",
        what: "Distribute and protect the individual circuits.",
        goesWrong: "Nuisance trips and heat-fatigued breakers that no longer trip at rating: both are warnings.",
        symptoms: "Nuisance trips, warm breakers, mystery outages on one circuit.",
        action: "Thermal scan and torque annually; replace heat-fatigued breakers.",
        cx: 50,
        cy: 38,
      },
      {
        id: "meter",
        name: "Metering",
        what: "Utility and tenant metering on the service.",
        goesWrong: "Failed CTs and wiring drift make bills wrong and load studies useless.",
        symptoms: "Bills that don't match usage, dead displays, drifting readings.",
        action: "Verify CT ratios and connections during shutdowns; recalibrate metering.",
        cx: 67,
        cy: 24,
      },
      {
        id: "lugs",
        name: "Lugs & terminations",
        what: "The bolted connections carrying full load current.",
        goesWrong: "Loose lugs are the #1 finding on infrared scans, and the #1 cause of electrical fires.",
        symptoms: "Hot spots on infrared, discoloured insulation at terminations.",
        action: "Annual IR scan; torque to spec on shutdown days; re-terminate damaged conductors.",
        cx: 36,
        cy: 44,
      },
      {
        id: "conduit",
        name: "Feeders & conduit",
        what: "The heavy conductors feeding the panel.",
        goesWrong: "Insulation ages invisibly; megger testing on shutdown days catches it before it faults.",
        symptoms: "Aging insulation flagged on megger, moisture in conduits.",
        action: "Megger feeders on planned shutdowns; seal conduit entries; schedule replacement by condition.",
        cx: 50,
        cy: 6,
      },
      {
        id: "door",
        name: "Enclosure",
        what: "Deadfront, door, and labelling.",
        goesWrong: "Missing labels and blocked access turn a 5-minute isolation into an hour, during a flood.",
        symptoms: "Missing labels, blocked access, panel used as a shelf.",
        action: "Labelling audit annually; enforce clearance; update directories after every change.",
        cx: 18,
        cy: 35,
      },
    ],
  },
  "controls": {
    image: "/equipment-renders/controls.webp",
    alt: "3D render of a building automation control panel",
    parts: [
      {
        id: "controller",
        name: "Controller",
        what: "The programmable brain scheduling equipment and setpoints.",
        goesWrong: "Obsolete controllers with dead batteries lose their programs in a power blip, and the building wakes up dumb.",
        symptoms: "Program lost after outages, offline points, clock drift.",
        action: "Battery replacement on schedule; back up programs; plan retrofits before parts vanish.",
        cx: 52,
        cy: 18,
      },
      {
        id: "modules",
        name: "I/O modules",
        what: "The relays and points wiring equipment into the controller.",
        goesWrong: "Single failed relays quietly strand one fan or valve in place for months.",
        symptoms: "One stuck fan or valve while everything else works, chattering relays.",
        action: "Point-to-point checkout annually; replace failed relays and spare critical modules.",
        cx: 53,
        cy: 33,
      },
      {
        id: "transformers",
        name: "Power supplies",
        what: "Step control power down to 24V.",
        goesWrong: "Undersized or aging transformers brown-out the panel and cause ghost faults.",
        symptoms: "Ghost faults, browning panels, hum.",
        action: "Voltage check under load; upsize where added devices exceed VA budget.",
        cx: 52,
        cy: 57,
      },
      {
        id: "wiring",
        name: "Field wiring",
        what: "The conduit and cabling out to sensors and equipment.",
        goesWrong: "Abandoned wires and undocumented changes make every future fix slower and riskier.",
        symptoms: "Undocumented splices, abandoned cable, mystery points.",
        action: "Panel cleanup and as-built updates with every project; label both ends.",
        cx: 66,
        cy: 47,
      },
      {
        id: "sensors",
        name: "Sensors",
        what: "Temperature, pressure, and CO2 inputs the system trusts blindly.",
        goesWrong: "Drifted sensors make good equipment do dumb things. Calibrated annually.",
        symptoms: "Rooms that never satisfy, sensors reading impossible values.",
        action: "Calibrate against reference annually; relocate sensors mounted in bad spots.",
        cx: 54,
        cy: 46,
      },
    ],
  },
  "pump": {
    image: "/equipment-renders/pump.webp",
    alt: "3D render of a base-mounted circulation pump",
    parts: [
      {
        id: "motor",
        name: "Motor",
        what: "Drives the pump; usually the loudest early-warning system in the room.",
        goesWrong: "Bearing whine and rising amp draw come before failure. Trending beats guessing.",
        symptoms: "Whine or growl, hot casing, rising amps.",
        action: "Amp and vibration trending; grease on schedule; align at every coupling service.",
        cx: 75,
        cy: 30,
      },
      {
        id: "coupling",
        name: "Coupling",
        what: "Connects motor to pump shaft, behind the guard.",
        goesWrong: "Misalignment eats couplings and bearings on both sides. Laser alignment pays for itself.",
        symptoms: "Rubber dust under the guard, clunk at start, misalignment wear.",
        action: "Inspect element at every service; laser align after any motor or pump work.",
        cx: 55,
        cy: 38,
      },
      {
        id: "seal",
        name: "Mechanical seal",
        what: "Keeps the pumped water inside the pump.",
        goesWrong: "A weeping seal is normal-ish; a dripping one is a countdown to a flooded mechanical room.",
        symptoms: "Drip trail from the seal housing, crusted glycol, short seal life.",
        action: "Weep monitoring; replace seals on drip rate; fix system pressure problems causing failures.",
        cx: 42,
        cy: 36,
      },
      {
        id: "impeller",
        name: "Impeller & volute",
        what: "The spinning wheel that actually moves the water.",
        goesWrong: "Cavitation chews impellers when suction conditions go wrong; it sounds like pumping gravel.",
        symptoms: "Gravel sound (cavitation), falling flow, motor loaded but no head.",
        action: "Check suction conditions and strainers; inspect impeller on performance drop.",
        cx: 27,
        cy: 39,
      },
      {
        id: "suction",
        name: "Suction & discharge",
        what: "The flanged connections to the building loop.",
        goesWrong: "Strainers blind off and valves seize in position. Gauges on both sides tell the truth.",
        symptoms: "Strainer pressure drop, gauge flutter, air in the loop.",
        action: "Blow down strainers monthly; verify valve positions; purge air at high points.",
        cx: 17,
        cy: 38,
      },
      {
        id: "gauge",
        name: "Gauges",
        what: "Pressure across the pump equals a health report.",
        goesWrong: "Missing or dead gauges mean nobody has looked in years.",
        symptoms: "Dead or pegged gauges, no baseline data.",
        action: "Replace failed gauges; log differential pressure every visit against baseline.",
        cx: 28,
        cy: 15,
      },
    ],
  },
  "gas-heater": {
    image: "/equipment-renders/gas-heater.webp",
    alt: "3D render of a suspended gas unit heater",
    parts: [
      {
        id: "burner",
        name: "Burner",
        what: "Fires gas across the heat exchanger tubes.",
        goesWrong: "Dust and lint fowl the burners in shop environments; lazy yellow flames make CO.",
        symptoms: "Lint-fouled flames, delayed ignition thumps, yellow tips.",
        action: "Burner clean and combustion analysis each fall; verify manifold pressure.",
        cx: 35,
        cy: 43,
      },
      {
        id: "exchanger",
        name: "Heat exchanger",
        what: "Transfers flame heat into the air stream.",
        goesWrong: "Cracks with age and cycling: a carbon monoxide risk directly over people's heads. Inspected annually.",
        symptoms: "Rust flakes below the unit, smell when heating starts, CO alarms.",
        action: "Annual visual and combustion test; replace cracked exchangers — no patching.",
        cx: 40,
        cy: 28,
      },
      {
        id: "fan",
        name: "Fan",
        what: "Pushes warehouse air through the hot exchanger.",
        goesWrong: "Dead fan, overheated exchanger, tripped limit: the classic no-heat call on the coldest day.",
        symptoms: "Buzzing motor, slow start, overheat trips.",
        action: "Motor and blade service each fall; verify limit operation.",
        cx: 67,
        cy: 35,
      },
      {
        id: "gasvalve",
        name: "Gas valve",
        what: "Meters and shuts off the gas supply.",
        goesWrong: "Valves stick after summers idle. Tested at fall startup, every unit, every year.",
        symptoms: "No heat on the first cold day, valve hum, lockouts.",
        action: "Fall startup test on every unit; replace sticking valves; leak-test connections.",
        cx: 41,
        cy: 54,
      },
      {
        id: "flue",
        name: "Flue",
        what: "Vents combustion gases through the roof.",
        goesWrong: "Condensation corrodes flues from inside; joints loosen with building vibration.",
        symptoms: "Condensate streaks, loose joints overhead, draft spillage.",
        action: "Inspect supports and joints annually; replace corroded sections.",
        cx: 56,
        cy: 11,
      },
      {
        id: "thermostat",
        name: "Thermostat & limits",
        what: "Runs the heater and protects it from itself.",
        goesWrong: "Failed limits either freeze the space or cook the unit. Cheap parts, big consequences.",
        symptoms: "Space never holds setpoint, short cycling, dead stat.",
        action: "Verify calibration and cycle rate each fall; relocate stats mounted in dead air.",
        cx: 26,
        cy: 49,
      },
    ],
  },
  "transfer-switch": {
    image: "/equipment-renders/transfer-switch.webp",
    alt: "3D render of an automatic transfer switch",
    parts: [
      {
        id: "mechanism",
        name: "Transfer mechanism",
        what: "The contacts that shift the building from grid to generator.",
        goesWrong: "Contacts pit and mechanisms stick from sitting still. Annual transfer testing under load proves it actually moves.",
        symptoms: "Failed or slow transfers during tests, chatter, welded contacts.",
        action: "Annual transfer test under load; contact inspection and lubrication per OEM.",
        cx: 49,
        cy: 26,
      },
      {
        id: "controller",
        name: "Controller",
        what: "Senses the outage, starts the generator, and times the transfer.",
        goesWrong: "Obsolete controllers with no parts support turn a component failure into a bypass project.",
        symptoms: "Missed exercise runs, alarm history nobody reviews, blank display.",
        action: "Verify exercise clock and settings each service; remote annunciation to a watched location.",
        cx: 65,
        cy: 26,
      },
      {
        id: "lugs",
        name: "Lugs & terminations",
        what: "Full building load passes through these bolted joints.",
        goesWrong: "Heat at the lugs shows on infrared long before failure.",
        symptoms: "Warm terminations on IR scan, discoloured conductor insulation.",
        action: "Infrared scan annually; torque on shutdown; re-terminate damaged cable.",
        cx: 55,
        cy: 41,
      },
      {
        id: "conduit",
        name: "Feeders",
        what: "Utility and generator feeders landing in the switch.",
        goesWrong: "Rodents, moisture, and old insulation: everything ages in conduit where nobody looks.",
        symptoms: "Moisture or rodent sign at entries, aged feeder insulation.",
        action: "Seal entries; megger feeders on shutdowns; schedule replacement by condition.",
        cx: 57,
        cy: 52,
      },
      {
        id: "vents",
        name: "Enclosure & ventilation",
        what: "Keeps the gear cool and protected.",
        goesWrong: "Blocked vents overheat the cabinet; dust ingress fouls the mechanism.",
        symptoms: "Cabinet heat, dust blankets on the mechanism.",
        action: "Clean filters and louvers each service; keep clearance around the cabinet.",
        cx: 17,
        cy: 42,
      },
    ],
  },
  "building-envelope": {
    image: "/equipment-renders/building-envelope.webp",
    alt: "3D cutaway of a commercial flat roof and wall assembly showing membrane, insulation, flashing, and drain",
    parts: [
      {
        id: "membrane",
        name: "Roof membrane",
        what: "The waterproof cap sheet over everything below — the only layer between BC rain and the building.",
        goesWrong: "UV aging, punctures from trades, and open laps. Field failures are rare; details fail first.",
        symptoms: "Blisters, cracks, exposed reinforcement, ponding rings that outlast the rain.",
        action: "Annual roof inspection spring and fall; patch punctures immediately; budget replacement by condition survey, not age alone.",
        cx: 55,
        cy: 20,
      },
      {
        id: "insulation",
        name: "Rigid insulation",
        what: "Keeps heat in and moves the dew point out of the assembly.",
        goesWrong: "Wet insulation from any leak above never dries in place — R-value gone for good.",
        symptoms: "Cold interior ceilings, energy creep, soft spots underfoot on the roof.",
        action: "Moisture scan every few years and after any leak; cut out and replace wet boards, don't roof over them.",
        cx: 30,
        cy: 42,
      },
      {
        id: "flashing",
        name: "Parapet & metal flashing",
        what: "Metal caps and membrane upturns where the roof meets walls and edges — where most leaks actually start.",
        goesWrong: "Wind lifts caps, fasteners back out, thermal movement opens joints a little more each year.",
        symptoms: "Stains on the wall below the parapet, loose or rattling metal, visible gaps at laps.",
        action: "Inspect every roof visit; refasten and reseal laps; replace sections that no longer shed water.",
        cx: 69,
        cy: 23,
      },
      {
        id: "drain",
        name: "Roof drain",
        what: "Gets water off the roof before it becomes a structural load and a leak-finder.",
        goesWrong: "Clogged strainers and debris dams cause ponding, and ponding finds every weak lap.",
        symptoms: "Standing water 48 hours after rain, overflow discharge running, silt rings.",
        action: "Clear strainers every spring and fall and after storms; verify flow; check seals at the drain bowl.",
        cx: 37,
        cy: 20,
      },
      {
        id: "overflow",
        name: "Overflow scupper",
        what: "The emergency exit for water when the primary drain blocks.",
        goesWrong: "Gets sealed over or blocked by debris exactly because it is rarely needed.",
        symptoms: "Water marks at the scupper, staining down the facade below it.",
        action: "Confirm it's open at every inspection; it's the difference between a puddle and a structural load.",
        cx: 60,
        cy: 29,
      },
      {
        id: "sealant",
        name: "Sealant joints",
        what: "Caulked joints at transitions, penetrations, and dissimilar materials.",
        goesWrong: "Sealant ages out on a 10–15 year clock: UV, movement, and adhesion loss.",
        symptoms: "Cracked, chalky, or debonded beads; hairline gaps you can slide a card into.",
        action: "Rotating joint-replacement program by elevation; annual review of the highest-exposure joints.",
        cx: 62,
        cy: 36,
      },
      {
        id: "barrier",
        name: "Air & water barrier",
        what: "The continuous layer behind the cladding that keeps bulk water and air leakage out of the wall.",
        goesWrong: "Discontinuities at transitions and penetrations — a barrier is only as good as its worst detail.",
        symptoms: "Drafts, interior staining at windows, efflorescence on masonry.",
        action: "Inspect at any cladding opening; verify continuity at every renovation before the wall closes up.",
        cx: 55,
        cy: 53,
      },
    ],
  },
  "ev-charger": {
    image: "/equipment-renders/ev-charger.webp",
    alt: "Commercial dual-port EV charging station cutaway",
    parts: [
      {
        id: "display",
        name: "Display & payment",
        what: "The interface residents and visitors interact with: session status, billing, and fault messages.",
        goesWrong: "Screen failures and connectivity drops that quietly stop billing.",
        symptoms: "Blank or frozen screens, sessions that don't log, complaints about payment.",
        action: "Firmware updates and network checks on the annual visit; verify billing records against sessions.",
        cx: 48,
        cy: 17,
      },
      {
        id: "electronics",
        name: "Contactor & control boards",
        what: "The switching and metering electronics that start, stop, and measure every charge.",
        goesWrong: "Contactor pitting from thousands of cycles, board failures from surges and moisture.",
        symptoms: "Chattering relays, sessions that end early, error codes on the display.",
        action: "Annual internal inspection; torque power terminations; verify surge protection is intact.",
        cx: 47,
        cy: 30,
      },
      {
        id: "connector",
        name: "Charging connector",
        what: "The J1772/CCS handle drivers plug in dozens of times a day.",
        goesWrong: "Dropped connectors crack housings and bend pins; worn latches lose connection mid-charge.",
        symptoms: "Charging that stops when the cable is bumped, visible pin damage, loose latch.",
        action: "Inspect pins and latch each visit; replace worn connectors before they damage vehicle ports.",
        cx: 34,
        cy: 35,
      },
      {
        id: "cable",
        name: "Charging cable",
        what: "The heavy copper cable between pedestal and vehicle.",
        goesWrong: "Vehicles drive over cables; insulation cracks in cold weather; strain reliefs pull out.",
        symptoms: "Kinks, cuts, exposed conductor, ground-fault trips.",
        action: "Condition check every visit; replace damaged cables immediately — a damaged EV cable is a life-safety issue.",
        cx: 28,
        cy: 52,
      },
      {
        id: "pedestal",
        name: "Pedestal & enclosure",
        what: "The weatherproof housing taking the bumps, salt, and rain of a parkade or lot.",
        goesWrong: "Corrosion at the base, cracked panels from impacts.",
        symptoms: "Rust streaks, loose doors, water inside the cabinet.",
        action: "Inspect seals and anchors annually; touch up coating before corrosion spreads.",
        cx: 49,
        cy: 48,
      },
      {
        id: "base",
        name: "Base & conduit",
        what: "The concrete pad and the feeders that bring power from the panel.",
        goesWrong: "Water wicks up conduits into the cabinet; pads crack and tilt from vehicle impacts.",
        symptoms: "Tilted pedestal, moisture staining inside the base compartment.",
        action: "Verify conduit seals and pad condition annually; check bonding and grounding.",
        cx: 49,
        cy: 62,
      },
    ],
  },
  "led-lighting": {
    image: "/equipment-renders/led-lighting.webp",
    alt: "Industrial LED high-bay fixture cutaway",
    parts: [
      {
        id: "array",
        name: "LED array",
        what: "The board of diodes producing the light — rated for tens of thousands of hours, if the heat is managed.",
        goesWrong: "Individual diodes fail dark or discoloured when heat builds up.",
        symptoms: "Dark patches, colour shift, dimmer output than neighbouring fixtures.",
        action: "Replace boards or fixtures showing early diode failure; check heat-sink contact.",
        cx: 57,
        cy: 31,
      },
      {
        id: "driver",
        name: "Driver",
        what: "The power supply converting building power for the LEDs — the part that actually fails first.",
        goesWrong: "Electrolytic capacitors dry out with heat; surges kill drivers outright.",
        symptoms: "Flickering, strobing, dead fixtures with power present.",
        action: "Replace failed drivers like-for-like; add surge protection at the panel for banks of fixtures.",
        cx: 42,
        cy: 22,
      },
      {
        id: "heatsink",
        name: "Heat sink",
        what: "The finned aluminum body that keeps the diodes cool enough to live their rated life.",
        goesWrong: "Dust blankets the fins in warehouses; heat shortens LED and driver life.",
        symptoms: "Fixture hot to the touch, early diode failures, dust visibly caked.",
        action: "Blow down fins during high-level cleaning cycles; verify airflow around fixtures.",
        cx: 40,
        cy: 45,
      },
      {
        id: "lens",
        name: "Lens & optics",
        what: "The prismatic lens spreading light evenly across the floor below.",
        goesWrong: "Dust and yellowing steal lumens you're paying for.",
        symptoms: "Dim aisles under working fixtures, visible grime on the lens.",
        action: "Clean lenses on the relamp/maintenance cycle; replace UV-yellowed optics.",
        cx: 50,
        cy: 57,
      },
      {
        id: "sensor",
        name: "Occupancy sensor",
        what: "Switches or dims the fixture when nobody's below it — where the payback lives.",
        goesWrong: "Sensors stick on (wasting energy) or off (dark aisles), or lose their coverage aim.",
        symptoms: "Lights on in empty aisles all night, or workers in the dark waving their arms.",
        action: "Test and re-aim sensors annually; verify time delays match how the space is used.",
        cx: 72,
        cy: 33,
      },
      {
        id: "mount",
        name: "Mounting & cord",
        what: "The hook, chain, or pendant carrying the fixture over people's heads.",
        goesWrong: "Vibration loosens hardware; cords chafe at entry points.",
        symptoms: "Swaying fixtures, worn cord jackets, missing safety cables.",
        action: "Inspect mounting and safety cable at every high-level service; a falling fixture is a life-safety failure.",
        cx: 45,
        cy: 9,
      },
    ],
  },
  "loading-dock": {
    image: "/equipment-renders/loading-dock.webp",
    alt: "Warehouse loading dock cutaway with door and leveler",
    parts: [
      {
        id: "door",
        name: "Overhead door",
        what: "The sectional door cycling every truck, all day, all winter.",
        goesWrong: "Panels get hit by forklifts and loads; rollers wear; doors rack out of square.",
        symptoms: "Doors that bind, slam, daylight visible when closed.",
        action: "Quarterly inspection of panels, rollers, and tracks; keep spare panels for the inevitable.",
        cx: 49,
        cy: 28,
      },
      {
        id: "springs",
        name: "Torsion springs & track",
        what: "The counterbalance doing the heavy lifting on every cycle — and the most dangerous part to neglect.",
        goesWrong: "Springs fatigue and snap; cables fray; a snapped spring drops the door.",
        symptoms: "Door suddenly heavy, visible cable fray, gaps in the spring coil.",
        action: "Spring and cable inspection quarterly by a trained tech — never by building staff.",
        cx: 48,
        cy: 12,
      },
      {
        id: "leveler",
        name: "Dock leveler",
        what: "The hydraulic plate bridging truck bed to floor under every pallet.",
        goesWrong: "Hydraulics drift under load; lips crack; pit debris jams the mechanism.",
        symptoms: "Levelers that sag mid-load, banging, visible hydraulic weep.",
        action: "Annual hydraulic service; clean the pit; verify working range against your truck mix.",
        cx: 50,
        cy: 50,
      },
      {
        id: "seal",
        name: "Dock seal & shelter",
        what: "Seals the gap around the truck so you're not heating the outdoors.",
        goesWrong: "Trucks crush and tear seals daily; torn seals leak weather and pests.",
        symptoms: "Visible tears, drafts at the dock, snow inside the door.",
        action: "Inspect quarterly; replace panels before the energy loss outruns the seal cost.",
        cx: 32,
        cy: 30,
      },
      {
        id: "bumpers",
        name: "Dock bumpers",
        what: "Rubber blocks absorbing a few million pounds of truck per year.",
        goesWrong: "They wear through to the fasteners, then trucks hit concrete.",
        symptoms: "Rubber worn to half thickness, exposed bolts, cracked dock face.",
        action: "Check on every visit; replacement is cheap — dock wall repair is not.",
        cx: 33,
        cy: 57,
      },
      {
        id: "chock",
        name: "Wheel restraint",
        what: "Keeps the trailer from creeping away from the dock with a forklift inside it.",
        goesWrong: "Chocks go missing; painted markings fade; drivers skip the step.",
        symptoms: "No chock in sight, no signage, near-miss reports.",
        action: "Replace missing chocks immediately; consider mechanical restraints for busy docks.",
        cx: 73,
        cy: 62,
      },
    ],
  },
  "fan-coil": {
    image: "/equipment-renders/fan-coil.webp",
    alt: "Ceiling fan coil unit cutaway",
    parts: [
      {
        id: "coil",
        name: "Heating/cooling coil",
        what: "The copper coil that conditions the suite from the building's water loop.",
        goesWrong: "Fins clog with dust; coils corrode and pinhole — inside a ceiling.",
        symptoms: "Weak heating or cooling, hissing, stains spreading on the ceiling.",
        action: "Annual coil inspection and cleaning; pressure-test suspect coils before they let go.",
        cx: 45,
        cy: 28,
      },
      {
        id: "blower",
        name: "Blower fans",
        what: "The small drums pushing air through the suite.",
        goesWrong: "Bearings dry out; blowers load up with the dust the filter missed.",
        symptoms: "Rumble or squeal above the ceiling, airflow you can barely feel.",
        action: "Clean and lube on the annual visit; replace noisy motors before residents complain twice.",
        cx: 48,
        cy: 45,
      },
      {
        id: "filter",
        name: "Filter",
        what: "The cheap part protecting the coil, the blower, and the resident's lungs.",
        goesWrong: "Nobody changes them — until airflow dies and coils clog.",
        symptoms: "Grey filters, dusty grilles, weak airflow.",
        action: "Change 2–4 times per year; it's the highest-value 5 minutes in the suite.",
        cx: 16,
        cy: 28,
      },
      {
        id: "drainpan",
        name: "Drain pan & line",
        what: "Catches cooling-season condensate and sends it away.",
        goesWrong: "Pans overflow when drains clog with slime — directly into the ceiling below.",
        symptoms: "Water stains, musty smell, drips at the access panel.",
        action: "Treat and clear the pan and line every cooling season; verify slope.",
        cx: 55,
        cy: 55,
      },
      {
        id: "valve",
        name: "Control valve & piping",
        what: "Modulates loop water through the coil on the thermostat's orders.",
        goesWrong: "Valves stick open (roasting suites) or closed (freezing them); unions weep.",
        symptoms: "Suites stuck hot or cold regardless of setpoint, small leaks at the valve.",
        action: "Exercise valves annually; replace failed actuators; tighten weeping unions.",
        cx: 80,
        cy: 35,
      },
      {
        id: "duct",
        name: "Duct collars",
        what: "The flexible connections distributing air to the rooms.",
        goesWrong: "Flex duct crushes and disconnects above ceilings; conditioned air heats the plenum.",
        symptoms: "One room with no airflow, whistling above the ceiling.",
        action: "Verify connections whenever the ceiling is open; replace crushed sections.",
        cx: 84,
        cy: 20,
      },
    ],
  },
  "water-heater": {
    image: "/equipment-renders/water-heater.webp",
    alt: "Cutaway of a gas hot water tank and tankless water heater",
    parts: [
      {
        id: "anode",
        name: "Anode rod & connections",
        what: "The sacrificial rod that corrodes so the tank doesn't, plus the hot and cold connections on top.",
        goesWrong: "The anode dissolves quietly; once it's gone, the tank starts rusting from the inside.",
        symptoms: "Rusty hot water, rotten-egg smell, corroded fittings.",
        action: "Pull and inspect the anode every 2–3 years; replace it for a fraction of a new tank.",
        cx: 33,
        cy: 11,
      },
      {
        id: "baffle",
        name: "Flue baffle",
        what: "The spiral baffle inside the central flue that slows combustion gases so heat transfers to the water.",
        goesWrong: "Scale and sediment around the flue cut efficiency year after year.",
        symptoms: "Longer recovery times, higher gas bills, rumbling.",
        action: "Annual flush; inspect the baffle when servicing the burner.",
        cx: 33,
        cy: 30,
      },
      {
        id: "insulation",
        name: "Tank & insulation",
        what: "The glass-lined steel tank wrapped in foam insulation.",
        goesWrong: "The lining cracks with age and thermal cycling — then the countdown to a leak starts.",
        symptoms: "Moisture at the base, rust streaks, popping sounds.",
        action: "Replace on age and condition — a failed tank drains into your mechanical room, or your ceiling.",
        cx: 24,
        cy: 33,
      },
      {
        id: "burner",
        name: "Burner",
        what: "The gas burner at the base that heats the tank.",
        goesWrong: "Sediment raining onto the burner chamber causes rumble, soot, and poor combustion.",
        symptoms: "Yellow flame, soot, slow heating.",
        action: "Annual burner clean and combustion check with the flush.",
        cx: 34,
        cy: 58,
      },
      {
        id: "gasvalve",
        name: "Gas valve & thermostat",
        what: "Controls gas flow and water temperature.",
        goesWrong: "Valves stick and thermostats drift, scalding or freezing the taps.",
        symptoms: "Water too hot or cold regardless of setting, pilot dropouts.",
        action: "Test and set temperature at every service; replace failing valves, never bypass.",
        cx: 23,
        cy: 49,
      },
      {
        id: "exchanger",
        name: "Tankless heat exchanger",
        what: "The copper heat exchanger where a tankless unit heats water on demand.",
        goesWrong: "Scale chokes the passages in hard-water areas; heat exchangers crack from thermal stress.",
        symptoms: "Fluctuating temperature, error codes, falling flow.",
        action: "Descale annually; check for exhaust leaks at the exchanger.",
        cx: 65,
        cy: 33,
      },
      {
        id: "fanvent",
        name: "Fan & venting",
        what: "The combustion fan and vent that exhaust a tankless unit.",
        goesWrong: "Blocked intakes and failed fans lock the unit out — usually mid-shower.",
        symptoms: "Lockout codes, vibration, condensation at the vent.",
        action: "Clear intakes and inspect venting every service.",
        cx: 65,
        cy: 15,
      },
    ],
  },
};
